# coding: utf-8

"""
    Pulp3 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.artifacts_api import ArtifactsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestArtifactsApi(unittest.TestCase):
    """ArtifactsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.artifacts_api.ArtifactsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_artifacts_create(self):
        """Test case for artifacts_create

        """
        pass

    def test_artifacts_delete(self):
        """Test case for artifacts_delete

        """
        pass

    def test_artifacts_list(self):
        """Test case for artifacts_list

        """
        pass

    def test_artifacts_read(self):
        """Test case for artifacts_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
