# coding: utf-8

"""
    Pulp3 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.users_api import UsersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_create(self):
        """Test case for users_create

        """
        pass

    def test_users_delete(self):
        """Test case for users_delete

        """
        pass

    def test_users_list(self):
        """Test case for users_list

        """
        pass

    def test_users_partial_update(self):
        """Test case for users_partial_update

        """
        pass

    def test_users_read(self):
        """Test case for users_read

        """
        pass

    def test_users_update(self):
        """Test case for users_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
