# coding: utf-8

"""
    Pulp3 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.content_api import ContentApi  # noqa: E501
from swagger_client.rest import ApiException


class TestContentApi(unittest.TestCase):
    """ContentApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.content_api.ContentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_content_file_create(self):
        """Test case for content_file_create

        """
        pass

    def test_content_file_list(self):
        """Test case for content_file_list

        """
        pass

    def test_content_file_read(self):
        """Test case for content_file_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
