# coding: utf-8

"""
    Pulp3 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.file_content import FileContent  # noqa: E501
from swagger_client.rest import ApiException


class TestFileContent(unittest.TestCase):
    """FileContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileContent(self):
        """Test FileContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.file_content.FileContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
