# coding: utf-8

"""
    Pulp3 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.progress_report import ProgressReport  # noqa: E501
from swagger_client.rest import ApiException


class TestProgressReport(unittest.TestCase):
    """ProgressReport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProgressReport(self):
        """Test ProgressReport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.progress_report.ProgressReport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
