# coding: utf-8

"""
    Pulp3 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tasks_api import TasksApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.tasks_api.TasksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tasks_cancel(self):
        """Test case for tasks_cancel

        """
        pass

    def test_tasks_delete(self):
        """Test case for tasks_delete

        """
        pass

    def test_tasks_list(self):
        """Test case for tasks_list

        """
        pass

    def test_tasks_read(self):
        """Test case for tasks_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
