# coding: utf-8

"""
    Pulp3 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.repositories_api import RepositoriesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRepositoriesApi(unittest.TestCase):
    """RepositoriesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.repositories_api.RepositoriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_repositories_create(self):
        """Test case for repositories_create

        """
        pass

    def test_repositories_delete(self):
        """Test case for repositories_delete

        """
        pass

    def test_repositories_list(self):
        """Test case for repositories_list

        """
        pass

    def test_repositories_partial_update(self):
        """Test case for repositories_partial_update

        """
        pass

    def test_repositories_read(self):
        """Test case for repositories_read

        """
        pass

    def test_repositories_update(self):
        """Test case for repositories_update

        """
        pass

    def test_repositories_versions_added_content(self):
        """Test case for repositories_versions_added_content

        """
        pass

    def test_repositories_versions_content(self):
        """Test case for repositories_versions_content

        """
        pass

    def test_repositories_versions_create(self):
        """Test case for repositories_versions_create

        """
        pass

    def test_repositories_versions_delete(self):
        """Test case for repositories_versions_delete

        """
        pass

    def test_repositories_versions_list(self):
        """Test case for repositories_versions_list

        """
        pass

    def test_repositories_versions_read(self):
        """Test case for repositories_versions_read

        """
        pass

    def test_repositories_versions_removed_content(self):
        """Test case for repositories_versions_removed_content

        """
        pass


if __name__ == '__main__':
    unittest.main()
