# coding: utf-8

"""
    Pulp3 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.remotes_api import RemotesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRemotesApi(unittest.TestCase):
    """RemotesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.remotes_api.RemotesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_remotes_file_create(self):
        """Test case for remotes_file_create

        """
        pass

    def test_remotes_file_delete(self):
        """Test case for remotes_file_delete

        """
        pass

    def test_remotes_file_list(self):
        """Test case for remotes_file_list

        """
        pass

    def test_remotes_file_partial_update(self):
        """Test case for remotes_file_partial_update

        """
        pass

    def test_remotes_file_read(self):
        """Test case for remotes_file_read

        """
        pass

    def test_remotes_file_sync(self):
        """Test case for remotes_file_sync

        """
        pass

    def test_remotes_file_update(self):
        """Test case for remotes_file_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
