# coding: utf-8

"""
    Pulp3 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.workers_api import WorkersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWorkersApi(unittest.TestCase):
    """WorkersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.workers_api.WorkersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_workers_list(self):
        """Test case for workers_list

        """
        pass

    def test_workers_read(self):
        """Test case for workers_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
