# coding: utf-8

"""
    Pulp3 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class ArtifactsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def artifacts_create(self, file, **kwargs):  # noqa: E501
        """artifacts_create  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.artifacts_create(file, async=True)
        >>> result = thread.get()

        :param async bool
        :param file file: The stored file. (required)
        :param int id:
        :param str href:
        :param datetime created: Timestamp of creation.
        :param int size: The size of the file in bytes.
        :param str md5: The MD5 checksum of the file if available.
        :param str sha1: The SHA-1 checksum of the file if available.
        :param str sha224: The SHA-224 checksum of the file if available.
        :param str sha256: The SHA-256 checksum of the file if available.
        :param str sha384: The SHA-384 checksum of the file if available.
        :param str sha512: The SHA-512 checksum of the file if available.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.artifacts_create_with_http_info(file, **kwargs)  # noqa: E501
        else:
            (data) = self.artifacts_create_with_http_info(file, **kwargs)  # noqa: E501
            return data

    def artifacts_create_with_http_info(self, file, **kwargs):  # noqa: E501
        """artifacts_create  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.artifacts_create_with_http_info(file, async=True)
        >>> result = thread.get()

        :param async bool
        :param file file: The stored file. (required)
        :param int id:
        :param str href:
        :param datetime created: Timestamp of creation.
        :param int size: The size of the file in bytes.
        :param str md5: The MD5 checksum of the file if available.
        :param str sha1: The SHA-1 checksum of the file if available.
        :param str sha224: The SHA-224 checksum of the file if available.
        :param str sha256: The SHA-256 checksum of the file if available.
        :param str sha384: The SHA-384 checksum of the file if available.
        :param str sha512: The SHA-512 checksum of the file if available.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['file', 'id', 'href', 'created', 'size', 'md5', 'sha1', 'sha224', 'sha256', 'sha384', 'sha512']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method artifacts_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'file' is set
        if ('file' not in params or
                params['file'] is None):
            raise ValueError("Missing the required parameter `file` when calling `artifacts_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'id' in params:
            form_params.append(('id', params['id']))  # noqa: E501
        if 'href' in params:
            form_params.append(('_href', params['href']))  # noqa: E501
        if 'created' in params:
            form_params.append(('created', params['created']))  # noqa: E501
        if 'file' in params:
            local_var_files['file'] = params['file']  # noqa: E501
        if 'size' in params:
            form_params.append(('size', params['size']))  # noqa: E501
        if 'md5' in params:
            form_params.append(('md5', params['md5']))  # noqa: E501
        if 'sha1' in params:
            form_params.append(('sha1', params['sha1']))  # noqa: E501
        if 'sha224' in params:
            form_params.append(('sha224', params['sha224']))  # noqa: E501
        if 'sha256' in params:
            form_params.append(('sha256', params['sha256']))  # noqa: E501
        if 'sha384' in params:
            form_params.append(('sha384', params['sha384']))  # noqa: E501
        if 'sha512' in params:
            form_params.append(('sha512', params['sha512']))  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['multipart/form-data', 'application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/artifacts/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def artifacts_delete(self, artifact_href, **kwargs):  # noqa: E501
        """artifacts_delete  # noqa: E501

        Remove Artifact only if it is not associated with any Content.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.artifacts_delete(artifact_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str artifact_href: URI of Artifact. e.g.: /artifacts/1/ (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.artifacts_delete_with_http_info(artifact_href, **kwargs)  # noqa: E501
        else:
            (data) = self.artifacts_delete_with_http_info(artifact_href, **kwargs)  # noqa: E501
            return data

    def artifacts_delete_with_http_info(self, artifact_href, **kwargs):  # noqa: E501
        """artifacts_delete  # noqa: E501

        Remove Artifact only if it is not associated with any Content.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.artifacts_delete_with_http_info(artifact_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str artifact_href: URI of Artifact. e.g.: /artifacts/1/ (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['artifact_href']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method artifacts_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'artifact_href' is set
        if ('artifact_href' not in params or
                params['artifact_href'] is None):
            raise ValueError("Missing the required parameter `artifact_href` when calling `artifacts_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'artifact_href' in params:
            path_params['{artifact_href}'] = params['artifact_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['multipart/form-data', 'application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/{artifact_href}/', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def artifacts_list(self, **kwargs):  # noqa: E501
        """artifacts_list  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.artifacts_list(async=True)
        >>> result = thread.get()

        :param async bool
        :param str cursor: The pagination cursor value.
        :param int page_size: Number of results to return per page.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.artifacts_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.artifacts_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def artifacts_list_with_http_info(self, **kwargs):  # noqa: E501
        """artifacts_list  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.artifacts_list_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str cursor: The pagination cursor value.
        :param int page_size: Number of results to return per page.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['cursor', 'page_size']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method artifacts_list" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'cursor' in params:
            query_params.append(('cursor', params['cursor']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['multipart/form-data', 'application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/artifacts/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def artifacts_read(self, artifact_href, **kwargs):  # noqa: E501
        """artifacts_read  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.artifacts_read(artifact_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str artifact_href: URI of Artifact. e.g.: /artifacts/1/ (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.artifacts_read_with_http_info(artifact_href, **kwargs)  # noqa: E501
        else:
            (data) = self.artifacts_read_with_http_info(artifact_href, **kwargs)  # noqa: E501
            return data

    def artifacts_read_with_http_info(self, artifact_href, **kwargs):  # noqa: E501
        """artifacts_read  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.artifacts_read_with_http_info(artifact_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str artifact_href: URI of Artifact. e.g.: /artifacts/1/ (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['artifact_href']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method artifacts_read" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'artifact_href' is set
        if ('artifact_href' not in params or
                params['artifact_href'] is None):
            raise ValueError("Missing the required parameter `artifact_href` when calling `artifacts_read`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'artifact_href' in params:
            path_params['{artifact_href}'] = params['artifact_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['multipart/form-data', 'application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/{artifact_href}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
