# coding: utf-8

"""
    Pulp3 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class RemotesApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def remotes_file_create(self, data, **kwargs):  # noqa: E501
        """remotes_file_create  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.remotes_file_create(data, async=True)
        >>> result = thread.get()

        :param async bool
        :param FileRemote data: (required)
        :return: FileRemote
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.remotes_file_create_with_http_info(data, **kwargs)  # noqa: E501
        else:
            (data) = self.remotes_file_create_with_http_info(data, **kwargs)  # noqa: E501
            return data

    def remotes_file_create_with_http_info(self, data, **kwargs):  # noqa: E501
        """remotes_file_create  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.remotes_file_create_with_http_info(data, async=True)
        >>> result = thread.get()

        :param async bool
        :param FileRemote data: (required)
        :return: FileRemote
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['data']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method remotes_file_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `remotes_file_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in params:
            body_params = params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/remotes/file/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='FileRemote',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def remotes_file_delete(self, file_remote_href, **kwargs):  # noqa: E501
        """remotes_file_delete  # noqa: E501

        Trigger an asynchronous delete task  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.remotes_file_delete(file_remote_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str file_remote_href: URI of File Remote. e.g.: /remotes/file/1/ (required)
        :return: AsnycOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.remotes_file_delete_with_http_info(file_remote_href, **kwargs)  # noqa: E501
        else:
            (data) = self.remotes_file_delete_with_http_info(file_remote_href, **kwargs)  # noqa: E501
            return data

    def remotes_file_delete_with_http_info(self, file_remote_href, **kwargs):  # noqa: E501
        """remotes_file_delete  # noqa: E501

        Trigger an asynchronous delete task  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.remotes_file_delete_with_http_info(file_remote_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str file_remote_href: URI of File Remote. e.g.: /remotes/file/1/ (required)
        :return: AsnycOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['file_remote_href']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method remotes_file_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'file_remote_href' is set
        if ('file_remote_href' not in params or
                params['file_remote_href'] is None):
            raise ValueError("Missing the required parameter `file_remote_href` when calling `remotes_file_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'file_remote_href' in params:
            path_params['{file_remote_href}'] = params['file_remote_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/{file_remote_href}/', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AsnycOperationResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def remotes_file_list(self, **kwargs):  # noqa: E501
        """remotes_file_list  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.remotes_file_list(async=True)
        >>> result = thread.get()

        :param async bool
        :param str cursor: The pagination cursor value.
        :param int page_size: Number of results to return per page.
        :return: InlineResponse2004
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.remotes_file_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.remotes_file_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def remotes_file_list_with_http_info(self, **kwargs):  # noqa: E501
        """remotes_file_list  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.remotes_file_list_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str cursor: The pagination cursor value.
        :param int page_size: Number of results to return per page.
        :return: InlineResponse2004
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['cursor', 'page_size']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method remotes_file_list" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'cursor' in params:
            query_params.append(('cursor', params['cursor']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/remotes/file/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2004',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def remotes_file_partial_update(self, file_remote_href, data, **kwargs):  # noqa: E501
        """remotes_file_partial_update  # noqa: E501

        Trigger an asynchronous partial update task  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.remotes_file_partial_update(file_remote_href, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str file_remote_href: URI of File Remote. e.g.: /remotes/file/1/ (required)
        :param FileRemote data: (required)
        :return: AsnycOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.remotes_file_partial_update_with_http_info(file_remote_href, data, **kwargs)  # noqa: E501
        else:
            (data) = self.remotes_file_partial_update_with_http_info(file_remote_href, data, **kwargs)  # noqa: E501
            return data

    def remotes_file_partial_update_with_http_info(self, file_remote_href, data, **kwargs):  # noqa: E501
        """remotes_file_partial_update  # noqa: E501

        Trigger an asynchronous partial update task  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.remotes_file_partial_update_with_http_info(file_remote_href, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str file_remote_href: URI of File Remote. e.g.: /remotes/file/1/ (required)
        :param FileRemote data: (required)
        :return: AsnycOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['file_remote_href', 'data']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method remotes_file_partial_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'file_remote_href' is set
        if ('file_remote_href' not in params or
                params['file_remote_href'] is None):
            raise ValueError("Missing the required parameter `file_remote_href` when calling `remotes_file_partial_update`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `remotes_file_partial_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'file_remote_href' in params:
            path_params['{file_remote_href}'] = params['file_remote_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in params:
            body_params = params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/{file_remote_href}/', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AsnycOperationResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def remotes_file_read(self, file_remote_href, **kwargs):  # noqa: E501
        """remotes_file_read  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.remotes_file_read(file_remote_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str file_remote_href: URI of File Remote. e.g.: /remotes/file/1/ (required)
        :return: FileRemote
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.remotes_file_read_with_http_info(file_remote_href, **kwargs)  # noqa: E501
        else:
            (data) = self.remotes_file_read_with_http_info(file_remote_href, **kwargs)  # noqa: E501
            return data

    def remotes_file_read_with_http_info(self, file_remote_href, **kwargs):  # noqa: E501
        """remotes_file_read  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.remotes_file_read_with_http_info(file_remote_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str file_remote_href: URI of File Remote. e.g.: /remotes/file/1/ (required)
        :return: FileRemote
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['file_remote_href']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method remotes_file_read" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'file_remote_href' is set
        if ('file_remote_href' not in params or
                params['file_remote_href'] is None):
            raise ValueError("Missing the required parameter `file_remote_href` when calling `remotes_file_read`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'file_remote_href' in params:
            path_params['{file_remote_href}'] = params['file_remote_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/{file_remote_href}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='FileRemote',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def remotes_file_sync(self, file_remote_href, data, **kwargs):  # noqa: E501
        """remotes_file_sync  # noqa: E501

        Trigger an asynchronous task to sync file content.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.remotes_file_sync(file_remote_href, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str file_remote_href: URI of File Remote. e.g.: /remotes/file/1/ (required)
        :param RepositorySyncURL data: (required)
        :return: AsnycOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.remotes_file_sync_with_http_info(file_remote_href, data, **kwargs)  # noqa: E501
        else:
            (data) = self.remotes_file_sync_with_http_info(file_remote_href, data, **kwargs)  # noqa: E501
            return data

    def remotes_file_sync_with_http_info(self, file_remote_href, data, **kwargs):  # noqa: E501
        """remotes_file_sync  # noqa: E501

        Trigger an asynchronous task to sync file content.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.remotes_file_sync_with_http_info(file_remote_href, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str file_remote_href: URI of File Remote. e.g.: /remotes/file/1/ (required)
        :param RepositorySyncURL data: (required)
        :return: AsnycOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['file_remote_href', 'data']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method remotes_file_sync" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'file_remote_href' is set
        if ('file_remote_href' not in params or
                params['file_remote_href'] is None):
            raise ValueError("Missing the required parameter `file_remote_href` when calling `remotes_file_sync`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `remotes_file_sync`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'file_remote_href' in params:
            path_params['{file_remote_href}'] = params['file_remote_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in params:
            body_params = params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/{file_remote_href}/sync/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AsnycOperationResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def remotes_file_update(self, file_remote_href, data, **kwargs):  # noqa: E501
        """remotes_file_update  # noqa: E501

        Trigger an asynchronous update task  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.remotes_file_update(file_remote_href, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str file_remote_href: URI of File Remote. e.g.: /remotes/file/1/ (required)
        :param FileRemote data: (required)
        :return: AsnycOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.remotes_file_update_with_http_info(file_remote_href, data, **kwargs)  # noqa: E501
        else:
            (data) = self.remotes_file_update_with_http_info(file_remote_href, data, **kwargs)  # noqa: E501
            return data

    def remotes_file_update_with_http_info(self, file_remote_href, data, **kwargs):  # noqa: E501
        """remotes_file_update  # noqa: E501

        Trigger an asynchronous update task  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.remotes_file_update_with_http_info(file_remote_href, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str file_remote_href: URI of File Remote. e.g.: /remotes/file/1/ (required)
        :param FileRemote data: (required)
        :return: AsnycOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['file_remote_href', 'data']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method remotes_file_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'file_remote_href' is set
        if ('file_remote_href' not in params or
                params['file_remote_href'] is None):
            raise ValueError("Missing the required parameter `file_remote_href` when calling `remotes_file_update`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `remotes_file_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'file_remote_href' in params:
            path_params['{file_remote_href}'] = params['file_remote_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in params:
            body_params = params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/{file_remote_href}/', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AsnycOperationResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
