# coding: utf-8

"""
    Pulp3 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class RepositoriesApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def repositories_create(self, data, **kwargs):  # noqa: E501
        """repositories_create  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_create(data, async=True)
        >>> result = thread.get()

        :param async bool
        :param Repository data: (required)
        :return: Repository
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.repositories_create_with_http_info(data, **kwargs)  # noqa: E501
        else:
            (data) = self.repositories_create_with_http_info(data, **kwargs)  # noqa: E501
            return data

    def repositories_create_with_http_info(self, data, **kwargs):  # noqa: E501
        """repositories_create  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_create_with_http_info(data, async=True)
        >>> result = thread.get()

        :param async bool
        :param Repository data: (required)
        :return: Repository
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['data']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method repositories_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `repositories_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in params:
            body_params = params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/repositories/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Repository',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def repositories_delete(self, repository_href, **kwargs):  # noqa: E501
        """repositories_delete  # noqa: E501

        Trigger an asynchronous task to delete a repository.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_delete(repository_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_href: URI of Repository. e.g.: /repositories/1/ (required)
        :return: AsnycOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.repositories_delete_with_http_info(repository_href, **kwargs)  # noqa: E501
        else:
            (data) = self.repositories_delete_with_http_info(repository_href, **kwargs)  # noqa: E501
            return data

    def repositories_delete_with_http_info(self, repository_href, **kwargs):  # noqa: E501
        """repositories_delete  # noqa: E501

        Trigger an asynchronous task to delete a repository.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_delete_with_http_info(repository_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_href: URI of Repository. e.g.: /repositories/1/ (required)
        :return: AsnycOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repository_href']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method repositories_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repository_href' is set
        if ('repository_href' not in params or
                params['repository_href'] is None):
            raise ValueError("Missing the required parameter `repository_href` when calling `repositories_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repository_href' in params:
            path_params['{repository_href}'] = params['repository_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/{repository_href}/', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AsnycOperationResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def repositories_list(self, **kwargs):  # noqa: E501
        """repositories_list  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_list(async=True)
        >>> result = thread.get()

        :param async bool
        :param str cursor: The pagination cursor value.
        :param int page_size: Number of results to return per page.
        :return: InlineResponse2005
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.repositories_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.repositories_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def repositories_list_with_http_info(self, **kwargs):  # noqa: E501
        """repositories_list  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_list_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str cursor: The pagination cursor value.
        :param int page_size: Number of results to return per page.
        :return: InlineResponse2005
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['cursor', 'page_size']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method repositories_list" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'cursor' in params:
            query_params.append(('cursor', params['cursor']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/repositories/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2005',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def repositories_partial_update(self, repository_href, data, **kwargs):  # noqa: E501
        """repositories_partial_update  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_partial_update(repository_href, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_href: URI of Repository. e.g.: /repositories/1/ (required)
        :param Repository data: (required)
        :return: Repository
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.repositories_partial_update_with_http_info(repository_href, data, **kwargs)  # noqa: E501
        else:
            (data) = self.repositories_partial_update_with_http_info(repository_href, data, **kwargs)  # noqa: E501
            return data

    def repositories_partial_update_with_http_info(self, repository_href, data, **kwargs):  # noqa: E501
        """repositories_partial_update  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_partial_update_with_http_info(repository_href, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_href: URI of Repository. e.g.: /repositories/1/ (required)
        :param Repository data: (required)
        :return: Repository
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repository_href', 'data']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method repositories_partial_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repository_href' is set
        if ('repository_href' not in params or
                params['repository_href'] is None):
            raise ValueError("Missing the required parameter `repository_href` when calling `repositories_partial_update`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `repositories_partial_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repository_href' in params:
            path_params['{repository_href}'] = params['repository_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in params:
            body_params = params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/{repository_href}/', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Repository',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def repositories_read(self, repository_href, **kwargs):  # noqa: E501
        """repositories_read  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_read(repository_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_href: URI of Repository. e.g.: /repositories/1/ (required)
        :return: Repository
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.repositories_read_with_http_info(repository_href, **kwargs)  # noqa: E501
        else:
            (data) = self.repositories_read_with_http_info(repository_href, **kwargs)  # noqa: E501
            return data

    def repositories_read_with_http_info(self, repository_href, **kwargs):  # noqa: E501
        """repositories_read  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_read_with_http_info(repository_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_href: URI of Repository. e.g.: /repositories/1/ (required)
        :return: Repository
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repository_href']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method repositories_read" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repository_href' is set
        if ('repository_href' not in params or
                params['repository_href'] is None):
            raise ValueError("Missing the required parameter `repository_href` when calling `repositories_read`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repository_href' in params:
            path_params['{repository_href}'] = params['repository_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/{repository_href}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Repository',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def repositories_update(self, repository_href, data, **kwargs):  # noqa: E501
        """repositories_update  # noqa: E501

        Trigger an asynchronous task to updatea repository.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_update(repository_href, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_href: URI of Repository. e.g.: /repositories/1/ (required)
        :param Repository data: (required)
        :return: AsnycOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.repositories_update_with_http_info(repository_href, data, **kwargs)  # noqa: E501
        else:
            (data) = self.repositories_update_with_http_info(repository_href, data, **kwargs)  # noqa: E501
            return data

    def repositories_update_with_http_info(self, repository_href, data, **kwargs):  # noqa: E501
        """repositories_update  # noqa: E501

        Trigger an asynchronous task to updatea repository.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_update_with_http_info(repository_href, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_href: URI of Repository. e.g.: /repositories/1/ (required)
        :param Repository data: (required)
        :return: AsnycOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repository_href', 'data']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method repositories_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repository_href' is set
        if ('repository_href' not in params or
                params['repository_href'] is None):
            raise ValueError("Missing the required parameter `repository_href` when calling `repositories_update`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `repositories_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repository_href' in params:
            path_params['{repository_href}'] = params['repository_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in params:
            body_params = params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/{repository_href}/', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AsnycOperationResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def repositories_versions_added_content(self, repository_version_href, **kwargs):  # noqa: E501
        """repositories_versions_added_content  # noqa: E501

        List added Content  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_versions_added_content(repository_version_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_version_href: URI of Repository Version. e.g.: /repositories/1/versions/1/ (required)
        :return: Content
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.repositories_versions_added_content_with_http_info(repository_version_href, **kwargs)  # noqa: E501
        else:
            (data) = self.repositories_versions_added_content_with_http_info(repository_version_href, **kwargs)  # noqa: E501
            return data

    def repositories_versions_added_content_with_http_info(self, repository_version_href, **kwargs):  # noqa: E501
        """repositories_versions_added_content  # noqa: E501

        List added Content  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_versions_added_content_with_http_info(repository_version_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_version_href: URI of Repository Version. e.g.: /repositories/1/versions/1/ (required)
        :return: Content
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repository_version_href']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method repositories_versions_added_content" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repository_version_href' is set
        if ('repository_version_href' not in params or
                params['repository_version_href'] is None):
            raise ValueError("Missing the required parameter `repository_version_href` when calling `repositories_versions_added_content`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repository_version_href' in params:
            path_params['{repository_version_href}'] = params['repository_version_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/{repository_version_href}/added_content/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Content',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def repositories_versions_content(self, repository_version_href, **kwargs):  # noqa: E501
        """repositories_versions_content  # noqa: E501

        List Content  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_versions_content(repository_version_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_version_href: URI of Repository Version. e.g.: /repositories/1/versions/1/ (required)
        :return: Content
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.repositories_versions_content_with_http_info(repository_version_href, **kwargs)  # noqa: E501
        else:
            (data) = self.repositories_versions_content_with_http_info(repository_version_href, **kwargs)  # noqa: E501
            return data

    def repositories_versions_content_with_http_info(self, repository_version_href, **kwargs):  # noqa: E501
        """repositories_versions_content  # noqa: E501

        List Content  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_versions_content_with_http_info(repository_version_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_version_href: URI of Repository Version. e.g.: /repositories/1/versions/1/ (required)
        :return: Content
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repository_version_href']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method repositories_versions_content" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repository_version_href' is set
        if ('repository_version_href' not in params or
                params['repository_version_href'] is None):
            raise ValueError("Missing the required parameter `repository_version_href` when calling `repositories_versions_content`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repository_version_href' in params:
            path_params['{repository_version_href}'] = params['repository_version_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/{repository_version_href}/content/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Content',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def repositories_versions_create(self, repository_version_href, data, **kwargs):  # noqa: E501
        """repositories_versions_create  # noqa: E501

        Trigger an asynchronous task to create a new repository version.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_versions_create(repository_version_href, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_version_href: URI of Repository Version. e.g.: /repositories/1/versions/ (required)
        :param RepositoryVersion data: (required)
        :return: AsnycOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.repositories_versions_create_with_http_info(repository_version_href, data, **kwargs)  # noqa: E501
        else:
            (data) = self.repositories_versions_create_with_http_info(repository_version_href, data, **kwargs)  # noqa: E501
            return data

    def repositories_versions_create_with_http_info(self, repository_version_href, data, **kwargs):  # noqa: E501
        """repositories_versions_create  # noqa: E501

        Trigger an asynchronous task to create a new repository version.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_versions_create_with_http_info(repository_version_href, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_version_href: URI of Repository Version. e.g.: /repositories/1/versions/ (required)
        :param RepositoryVersion data: (required)
        :return: AsnycOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repository_version_href', 'data']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method repositories_versions_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repository_version_href' is set
        if ('repository_version_href' not in params or
                params['repository_version_href'] is None):
            raise ValueError("Missing the required parameter `repository_version_href` when calling `repositories_versions_create`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `repositories_versions_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repository_version_href' in params:
            path_params['{repository_version_href}'] = params['repository_version_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in params:
            body_params = params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/{repository_version_href}/versions/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AsnycOperationResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def repositories_versions_delete(self, repository_version_href, **kwargs):  # noqa: E501
        """repositories_versions_delete  # noqa: E501

        Trigger an asynchronous task to delete a repositroy version.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_versions_delete(repository_version_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_version_href: URI of Repository Version. e.g.: /repositories/1/versions/1/ (required)
        :return: AsnycOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.repositories_versions_delete_with_http_info(repository_version_href, **kwargs)  # noqa: E501
        else:
            (data) = self.repositories_versions_delete_with_http_info(repository_version_href, **kwargs)  # noqa: E501
            return data

    def repositories_versions_delete_with_http_info(self, repository_version_href, **kwargs):  # noqa: E501
        """repositories_versions_delete  # noqa: E501

        Trigger an asynchronous task to delete a repositroy version.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_versions_delete_with_http_info(repository_version_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_version_href: URI of Repository Version. e.g.: /repositories/1/versions/1/ (required)
        :return: AsnycOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repository_version_href']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method repositories_versions_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repository_version_href' is set
        if ('repository_version_href' not in params or
                params['repository_version_href'] is None):
            raise ValueError("Missing the required parameter `repository_version_href` when calling `repositories_versions_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repository_version_href' in params:
            path_params['{repository_version_href}'] = params['repository_version_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/{repository_version_href}/', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AsnycOperationResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def repositories_versions_list(self, repository_version_href, **kwargs):  # noqa: E501
        """repositories_versions_list  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_versions_list(repository_version_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_version_href: URI of Repository Version. e.g.: /repositories/1/versions/ (required)
        :param str ordering: Which field to use when ordering the results.
        :param str cursor: The pagination cursor value.
        :param int page_size: Number of results to return per page.
        :return: InlineResponse2006
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.repositories_versions_list_with_http_info(repository_version_href, **kwargs)  # noqa: E501
        else:
            (data) = self.repositories_versions_list_with_http_info(repository_version_href, **kwargs)  # noqa: E501
            return data

    def repositories_versions_list_with_http_info(self, repository_version_href, **kwargs):  # noqa: E501
        """repositories_versions_list  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_versions_list_with_http_info(repository_version_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_version_href: URI of Repository Version. e.g.: /repositories/1/versions/ (required)
        :param str ordering: Which field to use when ordering the results.
        :param str cursor: The pagination cursor value.
        :param int page_size: Number of results to return per page.
        :return: InlineResponse2006
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repository_version_href', 'ordering', 'cursor', 'page_size']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method repositories_versions_list" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repository_version_href' is set
        if ('repository_version_href' not in params or
                params['repository_version_href'] is None):
            raise ValueError("Missing the required parameter `repository_version_href` when calling `repositories_versions_list`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repository_version_href' in params:
            path_params['{repository_version_href}'] = params['repository_version_href']  # noqa: E501

        query_params = []
        if 'ordering' in params:
            query_params.append(('ordering', params['ordering']))  # noqa: E501
        if 'cursor' in params:
            query_params.append(('cursor', params['cursor']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/{repository_version_href}/versions/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2006',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def repositories_versions_partial_update(self, repository_version_href, data, **kwargs):  # noqa: E501
        """repositories_versions_partial_update  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_versions_partial_update(repository_version_href, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_version_href: URI of Repository Version. e.g.: /repositories/1/versions/1/ (required)
        :param RepositoryVersion data: (required)
        :return: RepositoryVersion
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.repositories_versions_partial_update_with_http_info(repository_version_href, data, **kwargs)  # noqa: E501
        else:
            (data) = self.repositories_versions_partial_update_with_http_info(repository_version_href, data, **kwargs)  # noqa: E501
            return data

    def repositories_versions_partial_update_with_http_info(self, repository_version_href, data, **kwargs):  # noqa: E501
        """repositories_versions_partial_update  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_versions_partial_update_with_http_info(repository_version_href, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_version_href: URI of Repository Version. e.g.: /repositories/1/versions/1/ (required)
        :param RepositoryVersion data: (required)
        :return: RepositoryVersion
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repository_version_href', 'data']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method repositories_versions_partial_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repository_version_href' is set
        if ('repository_version_href' not in params or
                params['repository_version_href'] is None):
            raise ValueError("Missing the required parameter `repository_version_href` when calling `repositories_versions_partial_update`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `repositories_versions_partial_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repository_version_href' in params:
            path_params['{repository_version_href}'] = params['repository_version_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in params:
            body_params = params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/{repository_version_href}/', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='RepositoryVersion',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def repositories_versions_read(self, repository_version_href, **kwargs):  # noqa: E501
        """repositories_versions_read  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_versions_read(repository_version_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_version_href: URI of Repository Version. e.g.: /repositories/1/versions/1/ (required)
        :return: RepositoryVersion
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.repositories_versions_read_with_http_info(repository_version_href, **kwargs)  # noqa: E501
        else:
            (data) = self.repositories_versions_read_with_http_info(repository_version_href, **kwargs)  # noqa: E501
            return data

    def repositories_versions_read_with_http_info(self, repository_version_href, **kwargs):  # noqa: E501
        """repositories_versions_read  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_versions_read_with_http_info(repository_version_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_version_href: URI of Repository Version. e.g.: /repositories/1/versions/1/ (required)
        :return: RepositoryVersion
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repository_version_href']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method repositories_versions_read" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repository_version_href' is set
        if ('repository_version_href' not in params or
                params['repository_version_href'] is None):
            raise ValueError("Missing the required parameter `repository_version_href` when calling `repositories_versions_read`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repository_version_href' in params:
            path_params['{repository_version_href}'] = params['repository_version_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/{repository_version_href}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='RepositoryVersion',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def repositories_versions_removed_content(self, repository_version_href, **kwargs):  # noqa: E501
        """repositories_versions_removed_content  # noqa: E501

        List removed Content  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_versions_removed_content(repository_version_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_version_href: URI of Repository Version. e.g.: /repositories/1/versions/1/ (required)
        :return: Content
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.repositories_versions_removed_content_with_http_info(repository_version_href, **kwargs)  # noqa: E501
        else:
            (data) = self.repositories_versions_removed_content_with_http_info(repository_version_href, **kwargs)  # noqa: E501
            return data

    def repositories_versions_removed_content_with_http_info(self, repository_version_href, **kwargs):  # noqa: E501
        """repositories_versions_removed_content  # noqa: E501

        List removed Content  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_versions_removed_content_with_http_info(repository_version_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_version_href: URI of Repository Version. e.g.: /repositories/1/versions/1/ (required)
        :return: Content
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repository_version_href']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method repositories_versions_removed_content" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repository_version_href' is set
        if ('repository_version_href' not in params or
                params['repository_version_href'] is None):
            raise ValueError("Missing the required parameter `repository_version_href` when calling `repositories_versions_removed_content`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repository_version_href' in params:
            path_params['{repository_version_href}'] = params['repository_version_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/{repository_version_href}/removed_content/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Content',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def repositories_versions_update(self, repository_version_href, data, **kwargs):  # noqa: E501
        """repositories_versions_update  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_versions_update(repository_version_href, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_version_href: URI of Repository Version. e.g.: /repositories/1/versions/1/ (required)
        :param RepositoryVersion data: (required)
        :return: RepositoryVersion
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.repositories_versions_update_with_http_info(repository_version_href, data, **kwargs)  # noqa: E501
        else:
            (data) = self.repositories_versions_update_with_http_info(repository_version_href, data, **kwargs)  # noqa: E501
            return data

    def repositories_versions_update_with_http_info(self, repository_version_href, data, **kwargs):  # noqa: E501
        """repositories_versions_update  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.repositories_versions_update_with_http_info(repository_version_href, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str repository_version_href: URI of Repository Version. e.g.: /repositories/1/versions/1/ (required)
        :param RepositoryVersion data: (required)
        :return: RepositoryVersion
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repository_version_href', 'data']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method repositories_versions_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repository_version_href' is set
        if ('repository_version_href' not in params or
                params['repository_version_href'] is None):
            raise ValueError("Missing the required parameter `repository_version_href` when calling `repositories_versions_update`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `repositories_versions_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repository_version_href' in params:
            path_params['{repository_version_href}'] = params['repository_version_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in params:
            body_params = params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/{repository_version_href}/', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='RepositoryVersion',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
